<input type="hidden" name="campaign[{{ $key }}][campaign_name]" id="campaign_{{ $key }}_campaign_name" value="{{ $projectCampaign->name }}">
<input type="hidden" name="campaign[{{ $key }}][campaign_status]" id="campaign_{{ $key }}_campaign_status" value="{{ $projectCampaign->campaignStatus->id }}">
<input type="hidden" name="campaign[{{ $key }}][refq]" id="campaign_{{ $key }}_refq" value="{{ $projectCampaign->refq }}">
<input type="hidden" name="campaign[{{ $key }}][tide]" id="campaign_{{ $key }}_tide" value="{{ $projectCampaign->tide }}">
<input type="hidden" name="campaign[{{ $key }}][environmental_conditions]" id="campaign_{{ $key }}_environmental_conditions" value="{{ $projectCampaign->environmental_conditions }}">
<input type="hidden" name="campaign[{{ $key }}][utm]" id="campaign_{{ $key }}_utm" value="{{ $projectCampaign->utm }}">
<input type="hidden" name="campaign[{{ $key }}][water_depth]" id="campaign_{{ $key }}_water_depth" value="{{ $projectCampaign->water_depth }}">
<input type="hidden" name="campaign[{{ $key }}][sample_depth]" id="campaign_{{ $key }}_sample_depth" value="{{ $projectCampaign->sample_depth }}">
<input type="hidden" name="campaign[{{ $key }}][environmental_regime]" id="campaign_{{ $key }}_environmental_regime" value="{{ $projectCampaign->environmental_regime }}">
<input type="hidden" name="campaign[{{ $key }}][secchi_record]" id="campaign_{{ $key }}_secchi_record" value="{{ $projectCampaign->secchi_record }}">
<input type="hidden" name="campaign[{{ $key }}][floating_materials]" id="campaign_{{ $key }}_floating_materials" value="{{ $projectCampaign->floating_materials }}">
<input type="hidden" name="campaign[{{ $key }}][total_depth]" id="campaign_{{ $key }}_total_depth" value="{{ $projectCampaign->total_depth }}">
<input type="hidden" name="campaign[{{ $key }}][sedimentary_layer]" id="campaign_{{ $key }}_sedimentary_layer" value="{{ $projectCampaign->sedimentary_layer }}">
<input type="hidden" name="campaign[{{ $key }}][report_identification]" id="campaign_{{ $key }}_report_identification" value="{{ $projectCampaign->report_identification }}">
<input type="hidden" name="campaign[{{ $key }}][sampling_area]" id="campaign_{{ $key }}_sampling_area" value="{{ $projectCampaign->sampling_area }}">
<input type="hidden" name="campaign[{{ $key }}][organism_type]" id="campaign_{{ $key }}_organism_type" value="{{ $projectCampaign->organism_type }}">
<input type="hidden" name="campaign[{{ $key }}][popular_name]" id="campaign_{{ $key }}_popular_name" value="{{ $projectCampaign->popular_name }}">
<input type="hidden" name="campaign[{{ $key }}][effluent_type]" id="campaign_{{ $key }}_effluent_type" value="{{ $projectCampaign->effluent_type }}">
<input type="hidden" name="campaign[{{ $key }}][identification_pm]" id="campaign_{{ $key }}_identification_pm" value="{{ $projectCampaign->identification_pm }}">
<input type="hidden" name="campaign[{{ $key }}][pm_depth]" id="campaign_{{ $key }}_pm_depth" value="{{ $projectCampaign->pm_depth }}">
<input type="hidden" name="campaign[{{ $key }}][pm_diameter]" id="campaign_{{ $key }}_pm_diameter" value="{{ $projectCampaign->pm_diameter }}">
<input type="hidden" name="campaign[{{ $key }}][water_level]" id="campaign_{{ $key }}_water_level" value="{{ $projectCampaign->water_level }}">
<input type="hidden" name="campaign[{{ $key }}][oil_level]" id="campaign_{{ $key }}_oil_level" value="{{ $projectCampaign->oil_level }}">
<input type="hidden" name="campaign[{{ $key }}][sample_horizon]" id="campaign_{{ $key }}_sample_horizon" value="{{ $projectCampaign->sample_horizon }}">
<input type="hidden" name="campaign[{{ $key }}][field_measurements]" id="campaign_{{ $key }}_field_measurements" value="{{ $projectCampaign->field_measurements }}">
<input type="hidden" name="campaign[{{ $key }}][temperature]" id="campaign_{{ $key }}_temperature" value="{{ $projectCampaign->temperature }}">
<input type="hidden" name="campaign[{{ $key }}][humidity]" id="campaign_{{ $key }}_humidity" value="{{ $projectCampaign->humidity }}">
<input type="hidden" name="campaign[{{ $key }}][pressure]" id="campaign_{{ $key }}_pressure" value="{{ $projectCampaign->pressure }}">
