<input type="hidden" name="point_matrix[{{ $key }}][refq]" id="point_matrix_{{ $key }}_refq" value="{{ $projectPointMatrix->refq }}">
<input type="hidden" name="point_matrix[{{ $key }}][tide]" id="point_matrix_{{ $key }}_tide" value="{{ $projectPointMatrix->tide }}">
<input type="hidden" name="point_matrix[{{ $key }}][environmental_conditions]" id="point_matrix_{{ $key }}_environmental_conditions" value="{{ $projectPointMatrix->environmental_conditions }}">
<input type="hidden" name="point_matrix[{{ $key }}][utm]" id="point_matrix_{{ $key }}_utm" value="{{ $projectPointMatrix->utm }}">
<input type="hidden" name="point_matrix[{{ $key }}][water_depth]" id="point_matrix_{{ $key }}_water_depth" value="{{ $projectPointMatrix->water_depth }}">
<input type="hidden" name="point_matrix[{{ $key }}][sample_depth]" id="point_matrix_{{ $key }}_sample_depth" value="{{ $projectPointMatrix->sample_depth }}">
<input type="hidden" name="point_matrix[{{ $key }}][environmental_regime]" id="point_matrix_{{ $key }}_environmental_regime" value="{{ $projectPointMatrix->environmental_regime }}">
<input type="hidden" name="point_matrix[{{ $key }}][secchi_record]" id="point_matrix_{{ $key }}_secchi_record" value="{{ $projectPointMatrix->secchi_record }}">
<input type="hidden" name="point_matrix[{{ $key }}][floating_materials]" id="point_matrix_{{ $key }}_floating_materials" value="{{ $projectPointMatrix->floating_materials }}">
<input type="hidden" name="point_matrix[{{ $key }}][total_depth]" id="point_matrix_{{ $key }}_total_depth" value="{{ $projectPointMatrix->total_depth }}">
<input type="hidden" name="point_matrix[{{ $key }}][sedimentary_layer]" id="point_matrix_{{ $key }}_sedimentary_layer" value="{{ $projectPointMatrix->sedimentary_layer }}">
<input type="hidden" name="point_matrix[{{ $key }}][report_identification]" id="point_matrix_{{ $key }}_report_identification" value="{{ $projectPointMatrix->report_identification }}">
<input type="hidden" name="point_matrix[{{ $key }}][sampling_area]" id="point_matrix_{{ $key }}_sampling_area" value="{{ $projectPointMatrix->sampling_area }}">
<input type="hidden" name="point_matrix[{{ $key }}][organism_type]" id="point_matrix_{{ $key }}_organism_type" value="{{ $projectPointMatrix->organism_type }}">
<input type="hidden" name="point_matrix[{{ $key }}][popular_name]" id="point_matrix_{{ $key }}_popular_name" value="{{ $projectPointMatrix->popular_name }}">
<input type="hidden" name="point_matrix[{{ $key }}][effluent_type]" id="point_matrix_{{ $key }}_effluent_type" value="{{ $projectPointMatrix->effluent_type }}">
<input type="hidden" name="point_matrix[{{ $key }}][identification_pm]" id="point_matrix_{{ $key }}_identification_pm" value="{{ $projectPointMatrix->identification_pm }}">
<input type="hidden" name="point_matrix[{{ $key }}][pm_depth]" id="point_matrix_{{ $key }}_pm_depth" value="{{ $projectPointMatrix->pm_depth }}">
<input type="hidden" name="point_matrix[{{ $key }}][pm_diameter]" id="point_matrix_{{ $key }}_pm_diameter" value="{{ $projectPointMatrix->pm_diameter }}">
<input type="hidden" name="point_matrix[{{ $key }}][water_level]" id="point_matrix_{{ $key }}_water_level" value="{{ $projectPointMatrix->water_level }}">
<input type="hidden" name="point_matrix[{{ $key }}][oil_level]" id="point_matrix_{{ $key }}_oil_level" value="{{ $projectPointMatrix->oil_level }}">
<input type="hidden" name="point_matrix[{{ $key }}][sample_horizon]" id="point_matrix_{{ $key }}_sample_horizon" value="{{ $projectPointMatrix->sample_horizon }}">
<input type="hidden" name="point_matrix[{{ $key }}][field_measurements]" id="point_matrix_{{ $key }}_field_measurements" value="{{ $projectPointMatrix->field_measurements }}">
<input type="hidden" name="point_matrix[{{ $key }}][temperature]" id="point_matrix_{{ $key }}_temperature" value="{{ $projectPointMatrix->temperature }}">
<input type="hidden" name="point_matrix[{{ $key }}][humidity]" id="point_matrix_{{ $key }}_humidity" value="{{ $projectPointMatrix->humidity }}">
<input type="hidden" name="point_matrix[{{ $key }}][pressure]" id="point_matrix_{{ $key }}_pressure" value="{{ $projectPointMatrix->pressure }}">
